In [6]:
import pandas as pd
import numpy as np

df_near = pd.read_csv("../data/near_earth_asteroids_2025.csv")

df_near.rename({'q':'perihelion_distance_au', 'ad':'aphelion_distance_au', 'e':'eccentricity', 'a':'semimajor_axis_au'\
               , 'i':'inclination_deg','per':'orbital_period_days','n':'mean_motion_deg_day', 'rot_per':'rot_per_h',\
                'class':'class_code'}, axis=1, inplace=True)

df_close = pd.read_csv("../data/asteroid_close_approaches_2015_2035.csv")

df_close['close_approach_date'] = pd.to_datetime(df_close['close_approach_date'], format="ISO8601")

df_near.describe()

/tmp/ipykernel_202882/4288578708.py:4: DtypeWarning: Columns (0: name) have mixed types. Specify dtype option on import or set low_memory=False.
  df_near = pd.read_csv("../data/near_earth_asteroids_2025.csv")

,spkid,H,diameter_km,diameter_m,albedo,rot_per_h,eccentricity,semimajor_axis_au,inclination_deg,perihelion_distance_au,aphelion_distance_au,orbital_period_days,per_y,moid_au,moid_km,moid_lunar_distances,mean_motion_deg_day,condition_code,data_arc,data_arc_years
count,4.128100e+04,41279.000000,41281.000000,41281.000000,1204.000000,2181.000000,41281.000000,41281.000000,41281.000000,41281.000000,41281.000000,4.128100e+04,41281.000000,4.115000e+04,4.115000e+04,41150.000000,41281.000000,41279.000000,40875.000000,40875.000000
mean,2.852738e+07,23.718323,0.165592,165.588917,0.172680,17.249923,0.434323,1.757387,11.834802,0.914116,2.600654,9.706043e+02,2.657599,8.217933e-02,1.229385e+07,31.981713,0.530476,5.262506,1404.433394,3.845177
std,2.428187e+07,2.876761,0.403793,403.794103,0.144368,71.023057,0.176975,2.119936,10.549392,0.221873,4.221280,1.262065e+04,34.619953,9.638212e-02,1.441856e+07,37.509020,0.284677,3.169935,3099.025028,8.484637
min,3.002856e+06,9.170000,0.000475,0.500000,0.009000,0.000832,0.002800,0.461800,0.010000,0.069000,0.650000,1.150000e+02,0.314000,4.540000e-07,6.800000e+01,0.000000,0.000150,0.000000,0.000000,0.000000
25%,3.745029e+06,21.675000,0.024573,24.600000,0.047000,1.300000,0.300300,1.287000,4.350000,0.792000,1.650000,5.330000e+02,1.460000,1.160000e-02,1.735335e+06,4.510000,0.309600,2.000000,6.000000,0.020000
50%,2.046734e+07,24.040000,0.055266,55.300000,0.137000,4.400000,0.448200,1.679000,8.400000,0.962000,2.410000,7.950000e+02,2.180000,4.230000e-02,6.327990e+06,16.460000,0.453000,7.000000,22.000000,0.060000
75%,5.433661e+07,25.800000,0.165372,165.400000,0.256000,10.580000,0.563000,2.164000,16.550000,1.057000,3.340000,1.160000e+03,3.180000,1.210000e-01,1.810134e+07,47.090000,0.675200,8.000000,855.500000,2.345000
max,5.460683e+07,34.370000,37.675000,37675.000000,0.856000,1880.000000,0.996400,350.300000,165.600000,1.300000,699.320000,2.390000e+06,6560.000000,7.080000e-01,1.059153e+08,275.530000,3.141000,9.000000,46582.000000,127.530000

In [3]:
## We can use all rows where 'is_future' column is True as our inference 

df_near['first_obs'] = pd.to_datetime(df_near['first_obs'], format="ISO8601")
df_near['first_obs']

df_near['last_obs'] = pd.to_datetime(df_near['last_obs'], format="ISO8601")
df_near['last_obs']

0       2021-05-13
1       2026-03-20
2       2025-08-27
3       2026-03-22
4       2025-02-19
           ...
41276   2026-03-24
41277   2026-03-24
41278   2026-03-23
41279   2026-03-25
41280   2021-08-04
Name: last_obs, Length: 41281, dtype: datetime64[us]

In [4]:

df_near[df_near['last_obs'] < "2015-01-01"] ## all asteroids that were last seen before 2015. We can leave these out


df_close[df_close['designation'] == "2022 AP1"]
df_near['full_name'] = df_near['full_name'].apply(lambda x: x[x.index('('): ])
df_close['full_name'] = df_close['full_name'].apply(lambda x: x[x.index('('):] if '(' in x else np.nan)
df_close = df_close.dropna(how='any', subset=['full_name'], axis=0)
df_close['full_name'].isna().sum()

df_close.reset_index(drop=True, inplace=True)

In [24]:
df_close[df_close['close_approach_date'] > '2026-04-24']

,designation,full_name,close_approach_date,distance_au,dist_km,dist_lunar,distance_min_au,distance_max_au,velocity_km_s,v_rel_kmh,velocity_infinity_km_s,absolute_magnitude,is_future
23589,2022 KS,(2022 KS),2026-04-24 01:28:00,0.071687,10724234.0,27.90,0.061236,0.082139,4.833112,17399.0,4.825416,26.76,True
23590,2022 UU8,(2022 UU8),2026-04-25 06:31:00,0.022347,3343118.0,8.70,0.022137,0.022558,4.041643,14550.0,4.012035,27.97,True
23591,2023 HJ4,(2023 HJ4),2026-04-26 12:41:00,0.062647,9371818.0,24.38,0.039190,0.086127,12.386788,44592.0,12.383354,26.96,True
23592,2024 UG21,(2024 UG21),2026-04-27 08:30:00,0.061406,9186244.0,23.90,0.059284,0.063605,12.537502,45135.0,12.534040,27.17,True
23593,2004 US1,(2004 US1),2026-04-29 18:07:00,0.080826,12091392.0,31.46,0.080825,0.080827,16.683377,60060.0,16.681401,20.66,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...
27417,2025 AC1,(2025 AC1),2035-12-26 08:22:00,0.083559,12500228.0,32.52,0.066438,0.100799,8.709480,31354.0,8.705818,26.89,True
27418,2024 YF1,(2024 YF1),2035-12-27 13:18:00,0.089199,13343971.0,34.71,0.088964,0.141531,10.708675,38551.0,10.705885,23.54,True
27419,2025 PN7,(2025 PN7),2035-12-27 21:30:00,0.058551,8759067.0,22.79,0.058549,0.058552,1.831257,6593.0,1.806236,26.41,True
27420,2022 YS6,(2022 YS6),2035-12-28 08:54:00,0.024968,3735173.0,9.72,0.004201,0.046292,9.403958,33854.0,9.392603,26.86,True
27421,2024 WX15,(2024 WX15),2035-12-29 10:15:00,0.060425,9039430.0,23.52,0.059768,0.062458,5.940014,21384.0,5.932586,24.27,True

In [6]:
## Now we can finally join df_near and df_close on the column 'full_name'

df_near['full_name'] = df_near['full_name'].str.strip()
df_close['full_name'] = df_close['full_name'].str.strip()

In [7]:
import datetime
X_near = df_near.drop(['spkid','full_name','pdes','name', 'diameter_m','moid_lunar_distances','albedo', 'rot_per_h',\
                       'moid_km', 'per_y', 'data_arc_years', 'diameter_is_estimated','pha', 'first_obs', 'last_obs'], axis=1)
# per --> how many Earth days the asteroid takes to complete one full revolution
# per_y --> how many Earth years the asteroid takes to complete one full revolution
X_near['size_category'] = X_near['size_category'].apply(lambda x: x[0:x.index(" ")].strip())
y = df_near['pha']


X_near_no_moid = df_near.drop(['spkid','full_name','pdes','name', 'diameter_m','moid_lunar_distances','albedo','rot_per_h',\
                       'moid_km','moid_au', 'per_y', 'data_arc_years', 'diameter_is_estimated', 'first_obs', 'last_obs'], axis=1)
# the dataframe X_near_no_moid is the dataset we will use to fit a model to predict moid.
X_near_no_moid['size_category'] = X_near_no_moid['size_category'].apply(lambda x: x[0:x.index(" ")].strip())
y_moid = df_near['moid_au']

X_near_to_merge = df_near.drop(['spkid','pdes','name', 'diameter_m','moid_lunar_distances','albedo', 'rot_per_h',\
                       'moid_km', 'per_y', 'data_arc_years', 'diameter_is_estimated', 'first_obs', 'last_obs', 'H'], axis=1)
X_near_to_merge['size_category'] = X_near_to_merge['size_category'].apply(lambda x: x[0:x.index(" ")].strip())



#X_near.info()
X_near['moid_au'].describe()
X_close = df_close.copy()

X_close['is_future'] = np.where(X_close['close_approach_date'] >= datetime.datetime.now(), True, False)
X_close['is_future'].value_counts() # there are 44 less True values in column 'is_future'

X_merged = pd.merge(X_near_to_merge, X_close, on='full_name', how='inner').drop(['dist_km', 'dist_lunar'], axis=1)
y_absolute_magnitude = X_merged['absolute_magnitude']
X_merged.drop(["full_name", "designation", "close_approach_date","velocity_km_s", "velocity_infinity_km_s",\
               "distance_min_au","distance_max_au","absolute_magnitude"], axis=1, inplace=True)
# the dataset X_merged above will be used to predict 'absolute_magnitude'
X_merged

,pha,diameter_km,size_category,class_code,eccentricity,semimajor_axis_au,inclination_deg,perihelion_distance_au,aphelion_distance_au,orbital_period_days,moid_au,mean_motion_deg_day,condition_code,data_arc,distance_au,v_rel_kmh,is_future
0,False,4.200000,Large,AMO,0.5712,2.4740,9.40,1.061,3.89,1420.0,0.079700,0.2533,0.0,39281.0,0.082198,29695.0,False
1,True,1.000000,Large,APO,0.8270,1.0780,22.80,0.186,1.97,409.0,0.033500,0.8805,0.0,27807.0,0.053836,108801.0,False
2,False,5.700000,Large,AMO,0.5055,2.1490,23.96,1.063,3.24,1150.0,0.071700,0.3128,0.0,26251.0,0.089665,52010.0,True
3,True,3.400000,Large,APO,0.6505,1.7760,39.82,0.621,2.93,865.0,0.002770,0.4163,0.0,19295.0,0.089572,95428.0,False
4,True,3.400000,Large,APO,0.6505,1.7760,39.82,0.621,2.93,865.0,0.002770,0.4163,0.0,19295.0,0.086350,95105.0,True
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
27417,False,0.009873,Tiny,APO,0.2638,1.3000,4.32,0.957,1.64,541.0,0.018100,0.6651,8.0,2.0,0.020381,21554.0,False
27418,False,0.006958,Tiny,ATE,0.3022,0.9757,11.05,0.681,1.27,352.0,0.009540,1.0230,6.0,1.0,0.011928,39123.0,False
27419,False,0.010976,Tiny,APO,0.5668,2.1170,1.53,0.917,3.32,1130.0,0.000852,0.3199,9.0,3.0,0.027740,37764.0,False
27420,False,0.013692,Tiny,APO,0.7362,2.6870,1.66,0.709,4.66,1610.0,0.008870,0.2238,9.0,2.0,0.012432,69399.0,False
27421,False,0.024915,Tiny,APO,0.5170,2.0230,3.20,0.977,3.07,1050.0,0.039400,0.3427,8.0,2.0,0.057769,35862.0,False

In [8]:

numeric_columns = X_near.select_dtypes(include='number').columns.tolist()
numeric_columns

string_columns = X_near.select_dtypes(include='str').columns.tolist()
string_columns
numeric_columns

['H',
 'diameter_km',
 'eccentricity',
 'semimajor_axis_au',
 'inclination_deg',
 'perihelion_distance_au',
 'aphelion_distance_au',
 'orbital_period_days',
 'moid_au',
 'mean_motion_deg_day',
 'condition_code',
 'data_arc']

In [9]:
y = df_near['pha']

y_moid = df_near['moid_au']

y

0        False
1        False
2        False
3        False
4        False
         ...
41276    False
41277    False
41278    False
41279    False
41280     True
Name: pha, Length: 41281, dtype: bool

In [13]:
df_near
df_close

,designation,full_name,close_approach_date,distance_au,dist_km,dist_lunar,distance_min_au,distance_max_au,velocity_km_s,v_rel_kmh,velocity_infinity_km_s,absolute_magnitude,is_future
0,2022 AP1,(2022 AP1),2015-01-01 00:27:00,0.045100,6746806.0,17.55,0.013778,0.076571,11.891749,42810.0,11.886780,28.39,False
1,2015 AE45,(2015 AE45),2015-01-02 15:56:00,0.048239,7216474.0,18.77,0.048220,0.048258,7.065686,25436.0,7.057864,25.30,False
2,613286,(2005 YQ96),2015-01-02 21:46:00,0.026522,3967664.0,10.32,0.026522,0.026522,12.703378,45732.0,12.695467,20.63,False
3,2014 YQ34,(2014 YQ34),2015-01-03 13:29:00,0.079692,11921722.0,31.01,0.078275,0.081108,24.982094,89936.0,24.980756,24.16,False
4,2014 YE42,(2014 YE42),2015-01-03 15:00:00,0.010995,1644896.0,4.28,0.010971,0.011020,13.998882,50396.0,13.981561,23.40,False
...,...,...,...,...,...,...,...,...,...,...,...,...,...
27417,2025 AC1,(2025 AC1),2035-12-26 08:22:00,0.083559,12500228.0,32.52,0.066438,0.100799,8.709480,31354.0,8.705818,26.89,True
27418,2024 YF1,(2024 YF1),2035-12-27 13:18:00,0.089199,13343971.0,34.71,0.088964,0.141531,10.708675,38551.0,10.705885,23.54,True
27419,2025 PN7,(2025 PN7),2035-12-27 21:30:00,0.058551,8759067.0,22.79,0.058549,0.058552,1.831257,6593.0,1.806236,26.41,True
27420,2022 YS6,(2022 YS6),2035-12-28 08:54:00,0.024968,3735173.0,9.72,0.004201,0.046292,9.403958,33854.0,9.392603,26.86,True
27421,2024 WX15,(2024 WX15),2035-12-29 10:15:00,0.060425,9039430.0,23.52,0.059768,0.062458,5.940014,21384.0,5.932586,24.27,True

In [ ]:
X_merged.describe()

        diameter_km  eccentricity  ...   distance_au      v_rel_kmh
count  27422.000000  27422.000000  ...  27422.000000   27422.000000
mean       0.056491      0.387473  ...      0.043260   37997.355043
std        0.145297      0.180785  ...      0.029516   18856.933221
min        0.000548      0.002800  ...      0.000044     498.000000
25%        0.015222      0.243400  ...      0.016777   24932.250000
50%        0.027068      0.383050  ...      0.039466   34277.000000
75%        0.049030      0.530700  ...      0.068093   47823.750000
max        6.250000      0.957600  ...      0.099993  144687.000000

[8 rows x 13 columns]

In [ ]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder, StandardScaler
from sklearn.preprocessing import OneHotEncoder
from sklearn.compose import ColumnTransformer, make_column_selector
from sklearn.pipeline import Pipeline, make_pipeline
from sklearn.linear_model import LogisticRegression, LinearRegression
from sklearn.tree import DecisionTreeClassifier, DecisionTreeRegressor
from sklearn.ensemble import RandomForestClassifier, GradientBoostingClassifier, RandomForestRegressor, GradientBoostingRegressor
from sklearn.model_selection import cross_val_score, StratifiedKFold, train_test_split, GridSearchCV
from sklearn.impute import SimpleImputer
import numpy as np




# preprocessor = ColumnTransformer(
#     transformers=[
#         ('ohe', OneHotEncoder(handle_unknown='ignore', drop='first'),['class', 'size_category'] ),
#         ('simple_imputer', SimpleImputer(missing_values=np.nan, strategy="mean"), cols_with_nan),
      
#     ],
#     remainder='passthrough'
# )

categorical_transformer = Pipeline(
    steps = [
        ("one_hot_encoder", OneHotEncoder(handle_unknown='ignore', drop='first'))
    ]
)

numeric_transformer = Pipeline(
    steps = [
        ('simple_imputer', SimpleImputer(missing_values=np.nan, strategy='mean')),
        ('standard_scaler', StandardScaler())
    ]
)

preprocessor = ColumnTransformer(
    transformers = [
        ('categorical_transformer', categorical_transformer, make_column_selector(dtype_include=['object','category','str'])),
        ('numeric_transformer', numeric_transformer, make_column_selector(dtype_include='number'))
    ]
)

# pipeline_lr= Pipeline( steps= [
#     ('preprocessor', preprocessor),
#     ('standard_scaler', StandardScaler(), numeric_columns)
#     ('logistic_regression', LogisticRegression())
# ]
# )

# pipeline_rf = Pipeline( steps= [
#     ('preprocessor', preprocessor),
#     ('random_forest', RandomForestClassifier())
# ])

pipeline_lr = make_pipeline(preprocessor, LogisticRegression())
pipeline_rfc = make_pipeline(preprocessor, RandomForestClassifier())
pipeline_gbc = make_pipeline(preprocessor, GradientBoostingClassifier())

pipeline_dtr = make_pipeline(preprocessor, DecisionTreeRegressor())
pipeline_rfr = make_pipeline(preprocessor, RandomForestRegressor())
pipeline_gbr = make_pipeline(preprocessor, GradientBoostingRegressor())
pipeline_linreg = make_pipeline(preprocessor, LinearRegression())



pipelines_classification = {
    "Random Forest Classifier": pipeline_rfc,

    "Logistic Regression": pipeline_lr,

    "Gradient Boosting Classifier" : pipeline_gbc
}

pipelines_regression = {
    "Random Forest Regressor": pipeline_rfr,
    
    "Decision Tree Regressor": pipeline_dtr,

    "Gradient Boosting Regressor": pipeline_gbr,

    "Linear Regression": pipeline_linreg
}
# X_near, X_near_no_moid, X_merged

X_train, X_test, y_train, y_test = train_test_split(X_near, y, test_size=0.2, random_state=42)
X_train_no_moid, X_test_no_moid, y_train_moid, y_test_moid = train_test_split(X_near_no_moid, y_moid, test_size=0.2, random_state=42)
X_train_merged, X_test_merged, y_train_magnitude, y_test_magnitude = train_test_split(X_merged, y_absolute_magnitude, test_size=0.2, random_state=42)

trainsets = {"X_near": (X_train, y_train, "cat"), 
             
             "X_near_no_moid": (X_train_no_moid, y_train_moid, "num"),

             "X_merged":(X_train_merged, y_train_magnitude,"num")
             }

stratified_kf = StratifiedKFold(n_splits=5, shuffle=False)

def cross_val_all(trainsets, pipelines_c, pipelines_r):
    for name, (X_train, y_train, type) in trainsets.items():
        print(f"y_train entering for-loop: {y_train}")
        print(f"{name} train data cross-validation:\n")

        if type == "cat":

            for name, pipeline in pipelines_classification.items():

                if y_train.isna().sum() > 0:

                    y_nan_idx = y_train[y_train.isna()].index.tolist()
                    y_train = y_train.drop(y_nan_idx, axis=0).copy()
                    X_train = X_train.drop(y_nan_idx, axis=0).copy()
                    scores = cross_val_score(pipeline, X_train, y_train, cv=stratified_kf, scoring='f1_micro')
                    continue

                scores = cross_val_score(pipeline, X_train, y_train, cv=stratified_kf, scoring='f1_micro')

                print(f"{name:20s}: f1 score = {np.mean(scores):.3f} ± {np.std(scores):.3f}")
        else:
            
            for name, pipeline in pipelines_regression.items():

                if y_train.isna().sum() > 0:
                    print
                    y_nan_idx = y_train[y_train.isna()].index.tolist()
                    
                    y_train = y_train.drop(y_nan_idx, axis=0).copy()
                    X_train = X_train.drop(y_nan_idx, axis=0).copy()
                    scores = cross_val_score(pipeline, X_train, y_train, cv=5)
                    print(f"y_train after dropping indices: {y_train}")
                    continue
                print(f"y_train in second inner for-loop: {y_train}")
                scores = cross_val_score(pipeline, X_train, y_train, cv=5)
                print(f"{name:20s}: r2 score = {np.mean(scores):.3f} ± {np.std(scores):.3f}")

        print("====================")


cross_val_all(trainsets, pipelines_classification, pipelines_regression)
# scores_lr = cross_val_score(pipeline_lr, X_train, y_train, cv=stratified_kf, scoring='f1_micro')
# scores_rf = cross_val_score(pipeline_rf, X_train, y_train, cv=stratified_kf, scoring='f1_micro')

y_train entering for-loop: 17936    False
212      False
7589     False
1662     False
31895    False
         ...
6265     False
11284    False
38158    False
860      False
15795     True
Name: pha, Length: 33024, dtype: bool
X_near train data cross-validation:

Random Forest Classifier: f1 score = 0.999 ± 0.001
Logistic Regression : f1 score = 0.993 ± 0.001
Gradient Boosting Classifier: f1 score = 0.998 ± 0.000
====================
y_train entering for-loop: 17936    0.0631
212      0.3130
7589     0.0310
1662     0.2180
31895    0.0313
          ...
6265     0.1210
11284    0.0227
38158    0.0318
860      0.1590
15795    0.0427
Name: moid_au, Length: 33024, dtype: float64
X_near_no_moid train data cross-validation:

y_train after dropping indices: 17936    0.0631
212      0.3130
7589     0.0310
1662     0.2180
31895    0.0313
          ...
6265     0.1210
11284    0.0227
38158    0.0318
860      0.1590
15795    0.0427
Name: moid_au, Length: 32920, dtype: float64
y_train in second inner for-loop: 17936    0.0631
212      0.3130
7589     0.0310
1662     0.2180
31895    0.0313
          ...
6265     0.1210
11284    0.0227
38158    0.0318
860      0.1590
15795    0.0427
Name: moid_au, Length: 32920, dtype: float64
Decision Tree Regressor: r2 score = 0.635 ± 0.014
y_train in second inner for-loop: 17936    0.0631
212      0.3130
7589     0.0310
1662     0.2180
31895    0.0313
          ...
6265     0.1210
11284    0.0227
38158    0.0318
860      0.1590
15795    0.0427
Name: moid_au, Length: 32920, dtype: float64
Gradient Boosting Regressor: r2 score = 0.799 ± 0.005
y_train in second inner for-loop: 17936    0.0631
212      0.3130
7589     0.0310
1662     0.2180
31895    0.0313
          ...
6265     0.1210
11284    0.0227
38158    0.0318
860      0.1590
15795    0.0427
Name: moid_au, Length: 32920, dtype: float64
Linear Regression   : r2 score = 0.504 ± 0.166
====================
y_train entering for-loop: 16092    24.80
19703    26.84
5883     24.71
1574     24.30
1349     22.61
         ...
21575    31.77
5390     25.38
860      20.23
15795    25.59
23654    25.29
Name: absolute_magnitude, Length: 21937, dtype: float64
X_merged train data cross-validation:

y_train in second inner for-loop: 16092    24.80
19703    26.84
5883     24.71
1574     24.30
1349     22.61
         ...
21575    31.77
5390     25.38
860      20.23
15795    25.59
23654    25.29
Name: absolute_magnitude, Length: 21937, dtype: float64
Random Forest Regressor: r2 score = 0.998 ± 0.001
y_train in second inner for-loop: 16092    24.80
19703    26.84
5883     24.71
1574     24.30
1349     22.61
         ...
21575    31.77
5390     25.38
860      20.23
15795    25.59
23654    25.29
Name: absolute_magnitude, Length: 21937, dtype: float64
Decision Tree Regressor: r2 score = 0.996 ± 0.001
y_train in second inner for-loop: 16092    24.80
19703    26.84
5883     24.71
1574     24.30
1349     22.61
         ...
21575    31.77
5390     25.38
860      20.23
15795    25.59
23654    25.29
Name: absolute_magnitude, Length: 21937, dtype: float64
Gradient Boosting Regressor: r2 score = 0.997 ± 0.001
y_train in second inner for-loop: 16092    24.80
19703    26.84
5883     24.71
1574     24.30
1349     22.61
         ...
21575    31.77
5390     25.38
860      20.23
15795    25.59
23654    25.29
Name: absolute_magnitude, Length: 21937, dtype: float64
Linear Regression   : r2 score = 0.821 ± 0.004
====================

In [ ]:

from sklearn.metrics import f1_score
import joblib

best_model = pipelines_classification["Random Forest Classifier"]

best_model.fit(X_train, y_train)

# y_pred = best_model.predict(X_test)

# print(f1_score(y_pred, y_test))

best_model_columntransformer = best_model['columntransformer']
best_model_columntransformer.fit(X_train)

joblib.dump(best_model['randomforestclassifier'], './artifacts/best_model.pkl')
joblib.dump(best_model_columntransformer, './artifacts/best_model_columntransformer.pkl')

['./artifacts/best_model_columntransformer.pkl']

In [ ]:
from sklearn.metrics import r2_score
import joblib
import dill

best_model_abs_mag = pipelines_regression["Random Forest Regressor"]
column_transformer_abs_mag = best_model_abs_mag['columntransformer']

best_model_abs_mag.fit(X_train_merged, y_train_magnitude)
column_transformer_abs_mag.fit(X_train_merged)

y_pred_abs_mag = best_model_abs_mag.predict(X_test_merged)

print(f"r2 score: {r2_score(y_pred_abs_mag, y_test_magnitude)}")

with open('../artifacts/best_model_abs_mag.pkl', 'wb') as file:
    joblib.dump(best_model_abs_mag['randomforestregressor'], file)


with open('../artifacts/column_transformer_abs_mag.pkl', 'wb') as file:
    joblib.dump(column_transformer_abs_mag, file)

r2 score: 0.9979091280362288

In [ ]:
import matplotlib.pyplot as plt

mod = best_model_abs_mag

transformed = column_transformer_abs_mag.transform(X_train_merged).tolist()
X = pd.DataFrame(transformed, columns=[f"{col}" for col in column_transformer_abs_mag.get_feature_names_out()])
X = X_train_merged
baseline_score = mod.score(X, y_train_magnitude)
features = X.columns
features

hold = {}
for f in features:
    X_perm = X.copy()
    sum_scores = 0

    for n in range(10):

        X_perm[f] = np.random.permutation(X_perm[f])
        permuted_score = mod.score(X_perm, y_train_magnitude)
        if f == 'inclination_deg':
            print(permuted_score)

        sum_scores += permuted_score
    
    importance_score = baseline_score - sum_scores/10

    hold[f] = importance_score

0.9995388918995568
0.9995428277974232
0.9995514611658836
0.999544857519112
0.9995256676103614
0.9995538960557124
0.9995286550622191
0.9995523645608583
0.9995507645728313
0.9995333426830763

In [ ]:
features2, scores = zip(*sorted(hold.items(), key=lambda x: x[1]))


plt.subplots(figsize=(8,5))
plt.barh(features2, scores)

In [ ]:


moid_gbr_param_grid = {
    "gradientboostingregressor__n_estimators": [10, 30, 100, 300],
    "gradientboostingregressor__min_samples_leaf": [1, 2, 3],
    "gradientboostingregressor__max_depth": [2, 3, 5, 9]
}

moid_gbr_grid = GridSearchCV(
    pipelines_regression["Gradient Boosting Regressor"],
    moid_gbr_param_grid,
    cv=5,
    scoring="r2",
    n_jobs = -1,
    return_train_score=True
)

In [ ]:
y_train_na_idx = y_train_moid[y_train_moid.isna()].index.tolist()
y_train_moid.drop(y_train_na_idx, axis=0, inplace=True)
X_train_no_moid.drop(y_train_na_idx, axis=0, inplace=True)

moid_gbr_grid.fit(X_train_no_moid, y_train_moid)
moid_best_model = moid_gbr_grid.best_estimator_

y_na_idx = y_test_moid[y_test_moid.isna()].index.tolist()
y_test_moid.drop(y_na_idx, axis=0, inplace=True)
X_test_no_moid.drop(y_na_idx, axis=0, inplace=True)

y_pred_moid = moid_best_model.predict(X_test_no_moid)



print(f"GBR ---- R2 score: {r2_score(y_pred_moid, y_test_moid)}")

GBR ---- R2 score: 0.7787066908219039

In [ ]:


with open('../artifacts/moid_best_model.pkl', 'wb') as file:
    joblib.dump(moid_best_model['gradientboostingregressor'], file)

column_transformer_moid = moid_best_model['columntransformer']
column_transformer_moid.fit(X_train_no_moid, y_train_moid)

with open('../artifacts/column_transformer_moid.pkl', 'wb') as file:
    joblib.dump(column_transformer_moid, file)

In [ ]:
column_transformer_moid.get_params()
moid_gbr_grid
moid_best_model

X_merged.loc[55]

In [ ]:
X_train.iloc[2, :].to_json()

'{"H":25.9,"diameter_km":0.0234671832,"size_category":"Tiny","class_code":"APO","eccentricity":0.5977,"semimajor_axis_au":2.505,"inclination_deg":21.41,"perihelion_distance_au":1.008,"aphelion_distance_au":4.0,"orbital_period_days":1450.0,"moid_au":0.031,"mean_motion_deg_day":0.2486,"condition_code":8.0,"data_arc":2.0}'

In [ ]:
rf_param_grid = {
    "randomforestclassifier__n_estimators": [10, 70, 100, 500],
    "randomforestclassifier__max_depth": [2, 5, 7, 10, None],
    "randomforestclassifier__min_samples_leaf": [2, 3, 4]
}

rf_grid = GridSearchCV(
    pipelines["Random Forest"],
    rf_param_grid,
    cv=5,
    scoring='f1',
    n_jobs = -1,
    return_train_score=True
)

pipelines["Random Forest"].get_params().keys()

rf_grid.fit(X_train, y_train)
best_f1 = rf_grid.best_score_

print(f"Best parameters: {rf_grid.best_params_}")
print(f"\nBest score: {best_f1}")

Best parameters: {'randomforestclassifier__max_depth': None, 'randomforestclassifier__min_samples_leaf': 4, 'randomforestclassifier__n_estimators': 10}

Best score: 0.9890651371495665

In [ ]:
import joblib
import dill
from sklearn.metrics import f1_score

best_model_pha = rf_grid.best_estimator_
rf_grid_predict = best_model_pha.predict(X_test)

print(f1_score(rf_grid_predict, y_test)) #0.9857549857549858

column_transformer = best_model_pha['columntransformer']
column_transformer.fit(X_train, y_train)

0.9848484848484849

ColumnTransformer(transformers=[('categorical_transformer',
                                 Pipeline(steps=[('one_hot_encoder',
                                                  OneHotEncoder(drop='first',
                                                                handle_unknown='ignore'))]),
                                 ['size_category', 'class_code']),
                                ('numeric_transformer',
                                 Pipeline(steps=[('simple_imputer',
                                                  SimpleImputer()),
                                                 ('standard_scaler',
                                                  StandardScaler())]),
                                 ['H', 'diameter_km', 'albedo', 'rot_per_h',
                                  'eccentricity', 'semimajor_axis_au',
                                  'inclination_deg', 'perihelion_distance_au',
                                  'aphelion_distance_au', 'orbital_period_days',
                                  'moid_au', 'mean_motion_deg_day',
                                  'condition_code', 'data_arc'])])

In [ ]:
with open('../artifacts/best_model.pkl', 'wb') as file:
    joblib.dump(best_model_pha['randomforestclassifier'], file)

best_model_pha.get_params().keys()
best_model_pha['randomforestclassifier']

with open('../artifacts/best_model_columntransformer.pkl', 'wb') as file:
    joblib.dump(rf_grid.best_estimator_['columntransformer'], file)

In [ ]:
from sklearn.model_selection import KFold

skf = StratifiedKFold(n_splits=3)

for train, test in skf.split(X_near, y):
    print(np.bincount(y[train]))
    print(np.bincount(y[test]))

    print("==========")


kf = KFold(n_splits=3)
print("\n \n")
for train, test in kf.split(X_near, y):
    print(y[test])
    #print(np.bincount(y[test]))

    print("==========")

In [ ]:
js = X_near.to_json()
js
X_near

           H  diameter_km  ... condition_code data_arc
0      10.39    16.840000  ...            0.0  46582.0
1      15.59     2.706830  ...            0.0  41806.0
2      13.82     4.200000  ...            0.0  39281.0
3       9.17    37.675000  ...            0.0  37040.0
4      17.37     1.000000  ...            0.0  33947.0
...      ...          ...  ...            ...      ...
41276  20.85     0.240138  ...            9.0      2.0
41277  27.55     0.010976  ...            9.0      3.0
41278  27.07     0.013692  ...            9.0      2.0
41279  25.77     0.024915  ...            8.0      2.0
41280  20.52     0.279551  ...            0.0  22229.0

[41281 rows x 14 columns]